export default {
  id: 'acs', nombre: 'ACS', ticker: 'BME: ACS',
  categoria: 'Construcción, promoción y capital digital', fecha: '1 septiembre 2026',
  sobrelinea: 'Tres formas de cobrar el mismo ciclo de inversión',
  descripcion: 'Tesis técnica de ACS: Turner, Coravel, desarrollo de centros de datos, cuentas, valoración y cotización.',
  tesisCorta: 'ACS construye centros para terceros, desarrolla activos propios y comparte capital con GIP de BlackRock. La exposición es amplia. También lo es el precio que la bolsa ya paga por ella.',
  lectura: 'Calidad alta, valoración exigente',
  veredicto: 'Turner convierte demanda en cartera y caja sin asumir todo el riesgo inmobiliario. El desarrollo añade upside, pero también conexión, prealquiler y financiación a una acción que ya ha subido un 58%.',
  horizonte: '2026 a 2030',
  mercado: {
    precio: '€102,10', fecha: '31/08/2026', fechaLarga: '31 de agosto de 2026',
    inicioYtd: '31/12/2025', inicioUnAno: '29/08/2025',
    ytd: 20.3, unAno: 58.2, ibexYtd: 15.4, ibexUnAno: 33.7, ibexCierre: '19.974,1',
    comentario: 'ACS bate al IBEX en doce meses y en 2026, aunque perdió un 7,4% en agosto. La subida previa reduce el margen para que cartera y anuncios tarden en llegar al beneficio por acción.',
    metodo: 'Precio BME en euros. €84,85 al 31/12/2025, €64,55 al 29/08/2025 y €102,10 al 31/08/2026. Rentabilidad por precio, sin dividendos.',
  },
  metricas: [
    { etiqueta: 'Precio', valor: '€102,10', nota: 'Cierre del 31/08/2026' },
    { etiqueta: 'Rentabilidad 12 meses', valor: '+58,2%', nota: 'IBEX 35: +33,7%' },
    { etiqueta: 'Cartera 1S 2026', valor: '€105.856m', nota: '+21% comparable' },
    { etiqueta: 'Turner, margen EBITDA', valor: '4,0%', nota: '+64 puntos básicos' },
    { etiqueta: 'Inversión DC LTM', valor: '€746m', nota: 'Desarrollo propio' },
  ],
  resumen: 'ACS monetiza la expansión digital en varias capas. Turner y Dornan construyen; ACS Digital & Energy desarrolla y opera; Dragados ejecuta; Coravel, compartida al 50% con GIP, aporta capital y rotación. No se deben sumar cartera de obra, MW promovidos y valor de activos como si fueran la misma exposición económica.',
  favor: [
    'Turner crece con baja intensidad de capital y una cartera de €46.096m.',
    'Coravel permite reciclar capital sin abandonar la operación de la plataforma.',
    'La caja neta y el flujo operativo permiten financiar proyectos y remunerar al accionista.',
    'La guía de beneficio ordinario 2026 subió a crecimiento del 30% al 35%.',
  ],
  contra: [
    'Un PER prospectivo cercano a 25 veces exige crecimiento de beneficio por acción, no solo cartera.',
    'La ampliación de mayo diluye y señala necesidades de capital para la plataforma.',
    'Alcalá mantiene una brecha entre más de 100 MW objetivo y 50 MW de suministro documentado.',
    'El desarrollo propio añade riesgo de conexión, cliente, capex y financiación que Turner no asume.',
  ],
  miLectura: 'ACS es la exposición más completa de las cinco. La parte más defendible es Turner, que cobra durante la construcción. El upside de Coravel y los campus propios debe valorarse por contratos y capital recuperado, no por MW anunciados. Después de la subida, una buena empresa puede ser una inversión mediocre si la ejecución solo cumple lo ya descontado.',
  exposicion: {
    intro: 'La cadena combina ingresos de servicios con capital de desarrollo. Separar ambos evita confundir volumen de construcción con valor patrimonial.',
    cadena: [
      { titulo: 'Diseño y obra', texto: 'Turner, Dornan y Dragados cobran por entregar instalaciones críticas.' },
      { titulo: 'Promoción', texto: 'ACS Digital & Energy asegura suelo, conexión, permisos y clientes.' },
      { titulo: 'Capital', texto: 'Coravel comparte activos y nuevas inversiones al 50% con GIP.' },
      { titulo: 'Operación o venta', texto: 'La plataforma puede conservar ingresos o cristalizar valor mediante rotación.' },
    ],
    proyectos: [
      { nombre: 'Alcalá Data Center Campus', href: '/proyecto/acs-alcala-de-henares-campus', estado: 'En construcción', lectura: 'Más de 100 MW IT objetivo, pero solo 50 MW de suministro garantizado documentado y sin apertura confirmada.' },
      { nombre: 'La Puebla de Alfindén', href: '/proyecto/acs-la-puebla-de-alfinden-centro-datos', estado: 'En tramitación', lectura: '100 MW IT de primera fase, 150 MW concedidos en Peñaflor y €1.090m de contrata prevista.' },
      { nombre: 'Coravel', estado: 'JV 50/50', lectura: 'ACS aportó activos valorados en torno a €2.000m, con efectivo y earn-outs sujetos a hitos.' },
    ],
    nota: 'Los grandes contratos de Dallas y Waterford prueban la plataforma global, pero no son exposición española. Sirven para valorar capacidad de ejecución y demanda de capital.',
  },
  finanzas: {
    intro: 'El primer semestre combina crecimiento de Turner, cartera récord y caja neta.',
    bloques: [
      { titulo: 'Grupo, 1S 2026', filas: [['Ventas', '€26.168m'], ['EBITDA', '€1.618m'], ['Beneficio atribuible', '€510m'], ['Cartera', '€105.856m']] },
      { titulo: 'Caja y Turner', filas: [['Caja neta', '€1.006m'], ['Flujo operativo LTM', '€2.304m'], ['Cartera Turner', '€46.096m'], ['Margen EBITDA Turner', '4,0%']] },
    ],
    nota: 'La ampliación emitió 5,43 millones de acciones a €125 y captó €679,2m. Parte de la caja es reciente y está destinada a crecimiento, por lo que no conviene tratarla como exceso permanente.',
  },
  valoracion: {
    intro: 'La valoración ya reconoce buena parte del crecimiento. El análisis debe separar el múltiplo operativo de Turner del valor de los desarrollos.',
    bloques: [
      { etiqueta: 'Capitalización', valor: '≈ €28.292m', texto: 'Estimación observada al precio de referencia.' },
      { etiqueta: 'PER 2025', valor: '≈ 29,8×', texto: 'Capitalización sobre €950m de beneficio neto.' },
      { etiqueta: 'PER 2026 implícito', valor: '24,5 a 25,4×', texto: 'Aplicando la guía del 30% al 35% al beneficio ordinario 2025.' },
      { etiqueta: 'EV / EBITDA anualizado', valor: '≈ 8,4×', texto: 'Aproximación con EBITDA semestral y caja neta de junio.' },
    ],
    nota: 'El múltiplo EV es provisional porque ACS puede desplegar la caja. La prueba correcta para Coravel son cobros, earn-outs y retorno sobre el capital que permanece invertido.',
  },
  escenarios: [
    { nombre: 'Conservador', titulo: 'Cartera sin conversión', texto: 'Turner desacelera, los campus consumen caja y el beneficio ordinario queda por debajo de la guía.' },
    { nombre: 'Base', titulo: 'Ejecución de la guía', texto: 'Turner sostiene margen, Coravel cumple hitos y el beneficio crece entre 30% y 35%.' },
    { nombre: 'Favorable', titulo: 'Plataforma global', texto: 'Nuevos alquileres y rotaciones permiten crecer sin más dilución y mantienen cartera de construcción.' },
  ],
  seguimiento: [
    { indicador: 'Margen de Turner', confirma: 'Se mantiene en torno al 4% con cartera creciente.', alarma: 'Cae por debajo del 4% o aparecen cancelaciones.' },
    { indicador: 'Beneficio ordinario 2026', confirma: 'Al menos €1.114m, base de la guía.', alarma: 'Queda por debajo pese al crecimiento de cartera.' },
    { indicador: 'Prealquiler', confirma: 'Capex propio respaldado por clientes vinculantes.', alarma: 'Inversión relevante sin contrato.' },
    { indicador: 'Alcalá y La Puebla', confirma: 'Apertura, permisos y conexión avanzan con fechas.', alarma: 'Alcalá sigue sin operar o La Puebla no sale de tramitación.' },
    { indicador: 'Caja por acción', confirma: 'Earn-outs y rotaciones compensan capex y dilución.', alarma: 'Vuelve la deuda sin retorno por acción.' },
  ],
  fuentes: [
    { titulo: 'ACS, resultados del primer semestre de 2026', url: 'https://pressroom.grupoacs.com/noticias/acs-net-profit-510-million-1h2026', nota: 'Resultados, Turner, cartera, caja y capex digital.' },
    { titulo: 'ACS, resultados de 2025', url: 'https://www.grupoacs.com/ficheros_editor/File/03_accionistas_inversores/04_resultados_trimestrales/2025/FY/ACS%20Informe%20de%20Resultados%202025.pdf', nota: 'Base anual y beneficio ordinario.' },
    { titulo: 'ACS y GIP crean Coravel', url: 'https://www.grupoacs.com/ficheros_editor/File/03_accionistas_inversores/05_hechos_relevantes/2025/2025.11.14_OIR_Comunicaci%C3%B3n%20acuerdo%20Grupo%20ACS%20con%20GIP_ENG.pdf', nota: 'Estructura 50/50, activos y earn-outs.' },
    { titulo: 'CNMV, ampliación de capital de ACS', url: 'https://www.cnmv.es/webservices/verdocumento/ver?t=%7B7df6048d-995e-4405-abba-ed2ecb202633%7D', nota: 'Acciones, precio e importe captado.' },
    { titulo: 'BME, ficha de ACS', url: 'https://www.meff.es/esp/Derivados-Financieros/Ficha/ACS_ACS', nota: 'Cierre de mercado.' },
  ],
  limites: 'ACS no desglosa toda la rentabilidad de la plataforma digital. Cartera de construcción, inversión, MW IT, conexión y valor de activo miden cosas diferentes.',
}
