export default {
  id: 'ferrovial',
  nombre: 'Ferrovial',
  ticker: 'BME: FER',
  categoria: 'Construcción y desarrollo digital',
  fecha: '1 septiembre 2026',
  sobrelinea: 'Una opción digital dentro de una cartera global de infraestructuras',
  titulo: 'Ferrovial como inversión',
  descripcion: 'Tesis técnica de Ferrovial: centros de datos, Powernet, Alcobendas, cuentas, valoración, cotización y riesgos.',
  tesisCorta: 'Ferrovial combina obra para terceros, capacidad técnica y promoción propia. Alcobendas probará si esa integración crea valor de desarrollo o solo mueve margen de construcción dentro del grupo.',
  lectura: 'Opcionalidad, todavía pequeña',
  veredicto: 'El balance permite invertir y las capacidades existen. Faltan cliente ancla, calendario, financiación y retornos para pagar una prima por el negocio digital.',
  horizonte: '2027 a 2031',
  mercado: {
    precio: '€50,40', fecha: '31/08/2026', fechaLarga: '31 de agosto de 2026',
    inicioYtd: '31/12/2025', inicioUnAno: '01/09/2025',
    ytd: -8.9, unAno: 7.8, ibexYtd: 15.4, ibexUnAno: 33.7, ibexCierre: '19.974,1',
    comentario: 'La acción ha perdido terreno frente al IBEX en 2026 y durante los últimos doce meses. La caída de agosto fue fuerte, pero no hay una fuente primaria que la atribuya a centros de datos.',
    metodo: 'Precio BME en euros. €55,34 al 31/12/2025, €46,75 al 01/09/2025 y €50,40 al 31/08/2026. El índice usa 17.307,8, 14.939,4 y 19.974,1 puntos. No incluye dividendos ni el dividendo flexible de junio.',
  },
  metricas: [
    { etiqueta: 'Precio', valor: '€50,40', nota: 'Cierre del 31/08/2026' },
    { etiqueta: 'Rentabilidad 2026', valor: '-8,9%', nota: 'Precio, sin dividendos' },
    { etiqueta: 'EBITDA 1S 2026', valor: '€746m', nota: '+21,6% comparable' },
    { etiqueta: 'Caja neta ex infra', valor: '€1.307m', nota: 'Deuda de proyectos separada' },
    { etiqueta: 'MAD 01', valor: '40 MW IT', nota: '€153m de primera fase' },
  ],
  resumen: 'El negocio principal sigue siendo concesiones norteamericanas y construcción. Digital Infrastructure, creada en 2024, permanece dentro de Otros. La apuesta tiene tres piezas reales: experiencia de construcción, Powernet para sistemas técnicos y promoción de campus propios. Esa combinación es interesante, pero aún no genera información financiera separada.',
  favor: [
    'Alcobendas tiene permisos y acceso eléctrico; ya no es solo una reserva de suelo.',
    'Powernet añade diseño, instalación, mantenimiento y operación a la capacidad constructora.',
    'La caja neta ex infra permite financiar el capital inicial sin tensionar el balance de la matriz.',
    'El modelo de concesiones aporta disciplina para desarrollar, financiar y rotar activos.',
  ],
  contra: [
    'No hay cliente ancla, renta contratada, fecha de puesta en servicio ni yield on cost publicado.',
    'La construcción para una filial se elimina al consolidar y no crea beneficio externo por sí sola.',
    'La actividad digital es pequeña frente al valor de autopistas y aeropuertos.',
    'Una inversión superior a €1.000m competiría por capital sin demostrar todavía demanda contratada.',
  ],
  miLectura: 'Asignaría valor de opción, no un múltiplo de operador estabilizado. El punto de inflexión será un contrato de cliente y financiación sin recurso con economía publicada. Hasta entonces, comprar Ferrovial por centros de datos es comprar sobre todo las concesiones y recibir una opción digital difícil de valorar.',
  exposicion: {
    intro: 'Ferrovial intenta cubrir más partes del ciclo que un constructor convencional. El valor solo llegará al accionista si la promoción produce rentas, una venta externa o un valor superior al coste completo.',
    cadena: [
      { titulo: 'Suelo y conexión', texto: 'Digital Infrastructure asegura emplazamientos y derechos eléctricos en Alcobendas y Varsovia.' },
      { titulo: 'Diseño y construcción', texto: 'Ferrovial Construcción aporta experiencia, incluida la obra del campus Tier IV de Telefónica.' },
      { titulo: 'Sistemas y operación', texto: 'Powernet cubre instalaciones críticas, mantenimiento y operación técnica.' },
      { titulo: 'Propiedad o rotación', texto: 'El grupo puede conservar el activo, asociarse o venderlo después de reducir el riesgo.' },
    ],
    proyectos: [
      { nombre: 'Campus Valdelacasa, Alcobendas', href: '/proyecto/ferrovial-alcobendas-valdelacasa', estado: 'Permisos concedidos', lectura: 'MAD 01 identifica 40 MW IT y €153m. El campus anuncia más de 100 MW sin aclarar si toda la cifra es carga IT.' },
      { nombre: 'Campus de Varsovia', estado: 'Desarrollo inicial', lectura: 'Ferrovial y Budimex pagaron €56m por activos cuyo valor principal incluía derechos perpetuos de conexión.' },
      { nombre: 'Powernet', estado: 'Adquirida en 2025', lectura: 'Aporta capacidad técnica, pero el grupo no publica ingresos o margen digital por separado.' },
    ],
    nota: '€153m dividido entre 40 MW IT equivale a unos €3,83m por MW IT para MAD 01. No debe compararse sin ajustar alcance con el anuncio de más de €1.000m para todo el campus.',
  },
  finanzas: {
    intro: 'Las cuentas de 1S 2026 permiten financiar experimentos digitales, pero no muestran cuánto capital consume Digital Infrastructure.',
    bloques: [
      { titulo: 'Grupo, 1S 2026', filas: [['Ingresos', '€4.701m'], ['EBITDA ajustado', '€746m'], ['Beneficio atribuible', '€258m'], ['Liquidez', '€4.700m']] },
      { titulo: 'Construcción, 1S 2026', filas: [['Ingresos', '€3.700m'], ['EBITDA ajustado', '€223m'], ['Margen EBIT ajustado', '3,5%'], ['Cartera', '€18.046m']] },
    ],
    nota: 'El beneficio de 1S 2025 incluía €275m de ventas y deterioros frente a €28m en 2026. La caída del beneficio reportado no describe el negocio operativo. La caja de Construcción recibió anticipos que no deben anualizarse.',
  },
  valoracion: {
    intro: 'El EV sobre EBITDA consolidado distorsiona una compañía con deuda de proyectos, activos puestos en equivalencia y concesiones muy distintas. La suma de partes es más honesta.',
    bloques: [
      { etiqueta: 'Capitalización indicativa', valor: '≈ €36.300m', texto: '€50,40 por 720,6 millones de acciones de cierre de 2025. Es una aproximación, no una cifra ajustada por autocartera actual.' },
      { etiqueta: 'Peso de Norteamérica', valor: '86%', texto: 'Proporción del valor de consenso por suma de partes que el factbook atribuía a Norteamérica a diciembre de 2025.' },
      { etiqueta: 'Alcobendas, fase MAD 01', valor: '≈ 0,4%', texto: '€153m equivale a una fracción pequeña de la capitalización y no representa valor neto para el accionista.' },
      { etiqueta: 'Tratamiento digital', valor: 'Coste + opción', texto: 'Partir del capital invertido. Añadir prima solo al conocer alquiler, capex, deuda, plazo y rentabilidad.' },
    ],
    nota: 'No capitalizaría MW anunciados. Un derecho de conexión sin cliente reduce riesgo técnico, pero no demuestra que exista renta económica.',
  },
  escenarios: [
    { nombre: 'Conservador', titulo: 'Capacidad interna', texto: 'Powernet y la construcción aportan margen normal. Los campus avanzan despacio y Digital Infrastructure conserva valor cercano al coste.' },
    { nombre: 'Base', titulo: 'Primer campus financiado', texto: 'MAD 01 firma cliente, deuda de proyecto y un spread de retorno sobre coste de capital. Ferrovial retiene una participación y prueba el modelo.' },
    { nombre: 'Favorable', titulo: 'Plataforma replicable', texto: 'Alcobendas y Varsovia atraen clientes, se rota capital con ganancia y el grupo obtiene contratos externos de construcción y operación.' },
  ],
  seguimiento: [
    { indicador: 'MW IT contratados', confirma: 'Cliente ancla y prealquiler material antes de construir.', alarma: 'Permisos sin contratos durante 12 a 18 meses.' },
    { indicador: 'Capex por MW IT', confirma: 'Coste final próximo al alcance presupuestado de MAD 01.', alarma: 'Desviación sin aumento equivalente de renta.' },
    { indicador: 'Yield on cost', confirma: 'Spread claro frente al coste completo de capital.', alarma: 'La empresa no publica datos suficientes para estimarlo.' },
    { indicador: 'Capital FDI', confirma: 'Financiación sin recurso y coinversión limitan la caja de matriz.', alarma: 'Cae la caja neta sin clientes ni activos operativos.' },
    { indicador: 'Margen de Construcción', confirma: 'Contratos externos digitales sostienen o elevan el 3,5%.', alarma: 'Crece la obra interna sin caja consolidada.' },
  ],
  fuentes: [
    { titulo: 'Ferrovial, resultados del primer semestre de 2026', url: 'https://www.sec.gov/Archives/edgar/data/1468522/000162828026050224/q22026-ferrovialresultsp.htm', nota: 'Resultados, cartera, liquidez y caja neta ex infra.' },
    { titulo: 'Ferrovial, informe anual 2025', url: 'https://www.sec.gov/Archives/edgar/data/1468522/000162828026011789/fer-20251231.htm', nota: 'Digital Infrastructure, Powernet y estructura de segmentos.' },
    { titulo: 'Comunidad de Madrid, campus de Alcobendas', url: 'https://www.comunidad.madrid/noticias/2026/07/09/diaz-ayuso-anuncia-campus-centros-datos-alcobendas-1000-millones-euros-inversion', nota: 'Anuncio institucional del campus.' },
    { titulo: 'Histórico de FER en BME', url: 'https://stockanalysis.com/quote/bme/FER/history/', nota: 'Cierres para rentabilidad por precio.' },
    { titulo: 'BME, ficha del IBEX 35', url: 'https://www.meff.es/esp/Derivados-Financieros/Ficha/FIE_IBEX_35', nota: 'Contraste del cierre del índice.' },
  ],
  limites: 'Ferrovial no desglosa ingresos, EBITDA, capital comprometido ni rentabilidad de Digital Infrastructure. Las cifras de campus mezclan potencia disponible, potencia eléctrica y carga IT. El análisis evita sumarlas.',
}
