export default {
  id: 'iberdrola',
  nombre: 'Iberdrola',
  ticker: 'BME: IBE',
  categoria: 'Redes, energía y suelo electrificado',
  fecha: '1 septiembre 2026',
  sobrelinea: 'Electrificación con una opción sobre infraestructura digital',
  descripcion: 'Tesis técnica de Iberdrola: Echelon, suelo electrificado, conexiones, suministro, cuentas, valoración y cotización.',
  tesisCorta: 'Iberdrola no necesita poseer todo el edificio. Puede cobrar por suelo, conexión, infraestructura eléctrica y energía, además de conservar un 20% del vehículo con Echelon.',
  lectura: 'Sólida, pero poco pura',
  veredicto: 'La ventaja competitiva es real y replicable. El problema es la escala del grupo: incluso un campus grande tarda en mover el beneficio de una utility de €134.000 millones.',
  horizonte: '2027 a 2031',
  mercado: {
    precio: '€20,08', fecha: '31/08/2026', fechaLarga: '31 de agosto de 2026',
    inicioYtd: '31/12/2025', inicioUnAno: '01/09/2025',
    ytd: 9.8, unAno: 26.1, ibexYtd: 15.4, ibexUnAno: 33.7, ibexCierre: '19.974,1',
    comentario: 'Iberdrola ha ofrecido una subida fuerte con menor volatilidad que Solaria, pero ha quedado por detrás del IBEX. Esa diferencia encaja mejor con su carácter defensivo que con un rechazo específico a la estrategia digital.',
    metodo: 'Precio BME en euros. La ventana anual usa €15,92 al 01/09/2025 y €20,08 al 31/08/2026. El retorno de 2026 es aproximado con la serie de cierre disponible. Rentabilidad por precio, sin dividendos.',
  },
  metricas: [
    { etiqueta: 'Precio', valor: '€20,08', nota: 'Cierre del 31/08/2026' },
    { etiqueta: 'Rentabilidad 12 meses', valor: '+26,1%', nota: 'Precio, sin dividendos' },
    { etiqueta: 'EBITDA ajustado 1S', valor: '€8.050m', nota: '+7,4%' },
    { etiqueta: 'Conexión asegurada', valor: '723 MW', nota: 'Cartera CPD4Green' },
    { etiqueta: 'Participación Echelon', valor: '20%', nota: 'Echelon conserva hasta 80%' },
  ],
  resumen: 'La tesis es más amplia que la participación en Echelon. Iberdrola controla suelo, red, generación y contratos de suministro. CPD4Green declara más de 5 GW de cartera, 723 MW con conexión asegurada y 30 hectáreas. Madrid Sur es la prueba: 144 MW IT, 230 MW de conexión y unos 1 TWh de consumo anual. Aún faltan obras, cliente y decisión final de inversión.',
  favor: [
    'La escasez de conexión permite convertir electricidad y suelo en un producto conjunto.',
    'El 20% limita el capital de Iberdrola mientras conserva suministro y exposición al activo.',
    'Más de 11 TWh vendidos a clientes digitales globales acreditan capacidad comercial.',
    'Redes y generación permiten monetizar el mismo cliente en varias partes de la cadena.',
  ],
  contra: [
    'Madrid Sur no tiene cliente ancla, obras ni expediente local confirmado en el registro.',
    'Los 5 GW de cartera potencial no equivalen a proyectos financiados o permitidos.',
    'La deuda neta ajustada subió a €54.000m mientras el grupo mantiene un plan inversor enorme.',
    'A más de 20 veces beneficio ajustado, la acción no necesita una narrativa digital para parecer exigente.',
  ],
  miLectura: 'Iberdrola es una tesis de redes y electrificación con una opción digital, no una inversión pura en centros de datos. El 20% del edificio importa menos que los pagos por suelo electrificado, obra eléctrica y suministro de largo plazo. Para justificar valor adicional, el modelo debe repetirse y revelar retornos superiores a la generación convencional.',
  exposicion: {
    intro: 'La alianza reparte funciones de forma clara. Echelon desarrolla y opera. Iberdrola aporta los recursos eléctricos y una parte minoritaria del capital.',
    cadena: [
      { titulo: 'Suelo', texto: 'CPD4Green prepara emplazamientos y aporta 30 hectáreas a la cartera.' },
      { titulo: 'Conexión', texto: 'Iberdrola asegura acceso y desarrolla la infraestructura eléctrica del campus.' },
      { titulo: 'Energía', texto: 'El grupo suministra electricidad renovable 24/7 y añade generación asociada.' },
      { titulo: 'Participación', texto: 'Iberdrola conserva hasta el 20% de Echelon Iberdrola Digital Infra.' },
    ],
    proyectos: [
      { nombre: 'Echelon Iberdrola Madrid Sur', href: '/proyecto/echelon-iberdrola-madrid-sur', estado: 'Anunciado', lectura: '144 MW IT, 230 MW de conexión y más de €2.000m de inversión inicial. Sin municipio, obras o cliente confirmados.' },
      { nombre: 'CPD de Iberdrola en Toledo', href: '/proyecto/iberdrola-toledo-benquerencia', estado: 'Anunciado', lectura: 'Exposición directa adicional, todavía sin calendario operativo acreditado.' },
      { nombre: 'Suministro a tecnológicas', estado: 'Operativo', lectura: 'Más de 11 TWh anuales globales. Es demanda energética, no propiedad de centros.' },
    ],
    nota: 'El registro no presenta Aceca o Villaseca de la Sagra como ubicación confirmada de Madrid Sur. La asociación procede de prensa y no de las compañías.',
  },
  finanzas: {
    intro: 'El negocio digital debe competir con redes reguladas y generación por capital. En 1S 2026, el 63% de la inversión fue a redes.',
    bloques: [
      { titulo: 'Resultados 1S 2026', filas: [['EBITDA ajustado', '€8.050m'], ['Beneficio ajustado', '€3.565m'], ['Beneficio reportado', '€4.336m'], ['Inversión', '€7.000m']] },
      { titulo: 'Balance 1S 2026', filas: [['Deuda neta ajustada', '€54.000m'], ['Deuda / EBITDA', '3,5×'], ['FFO / deuda', '22,4%'], ['Liquidez', '€21.464m']] },
    ],
    nota: 'El beneficio reportado incluye €953m de plusvalía neta por México. Para valorar recurrencia, el beneficio ajustado es la medida útil. La guía 2026 apunta a crecimiento cómodamente superior al 8%.',
  },
  valoracion: {
    intro: 'La cotización refleja redes de crecimiento y ejecución fiable. El negocio digital aporta poco al beneficio actual y no debe valorarse como si los 5 GW estuvieran construidos.',
    bloques: [
      { etiqueta: 'Capitalización', valor: '≈ €134.000m', texto: '€20,08 por unos 6.673 millones de acciones.' },
      { etiqueta: 'PER 2025 ajustado', valor: '≈ 21,5×', texto: 'Capitalización frente a €6.231m de beneficio ajustado de 2025.' },
      { etiqueta: 'Dividendo indicado', valor: '≈ 3,4%', texto: '€0,685 por acción sobre el precio de referencia.' },
      { etiqueta: 'Madrid Sur', valor: 'Opción', texto: 'Valorar por capital comprometido y retornos del 20%, más contratos de suelo, red y energía.' },
    ],
    nota: 'Capitalización más deuda neta equivale de forma aproximada a 12 veces el EBITDA ajustado de 2025. No es un EV limpio por híbridos, minoritarios y metodologías regulatorias.',
  },
  escenarios: [
    { nombre: 'Conservador', titulo: 'Suministro sin escala', texto: 'Madrid Sur avanza despacio. Iberdrola vende energía, pero la participación digital no mueve las cuentas.' },
    { nombre: 'Base', titulo: 'Madrid Sur financiado', texto: 'Se firma cliente, financiación y decisión de inversión. El campus entra en servicio alrededor de 2030.' },
    { nombre: 'Favorable', titulo: 'Modelo repetible', texto: 'Los 723 MW conectados se convierten en varios campus y contratos energéticos con retornos publicados.' },
  ],
  seguimiento: [
    { indicador: 'Decisión de inversión', confirma: 'Madrid Sur toma FID y cierra financiación durante 2026 o 2027.', alarma: 'El proyecto termina 2026 sin decisión.' },
    { indicador: 'Cliente ancla', confirma: 'Contrato por una parte material de 144 MW IT.', alarma: 'Capex antes de prealquiler.' },
    { indicador: 'MW convertidos', confirma: 'Los 723 MW conectados aparecen con suelo, permisos y fechas.', alarma: 'Los 5 GW siguen siendo cartera comercial.' },
    { indicador: 'Capital de Iberdrola', confirma: 'La aportación permanece cercana al 20% y con retorno superior al coste.', alarma: 'Más capital sin mayor rentabilidad.' },
    { indicador: 'Desglose económico', confirma: 'Ingresos de suelo, conexión, suministro y JV visibles.', alarma: 'No se puede medir caja o retorno digital.' },
  ],
  fuentes: [
    { titulo: 'Iberdrola Factbook 2026', url: 'https://www.iberdrola.com/documents/20125/41740/Iberdrola_factbook_2026.pdf', nota: 'Cartera, conexión y estrategia digital.' },
    { titulo: 'Iberdrola y Echelon crean su sociedad conjunta', url: 'https://www.iberdrola.com/press-room/news/detail/echelon-iberdrola-digital-infra-created-invest-more-2-billion-euros-data-centres-spain', nota: 'Participaciones, inversión y Madrid Sur.' },
    { titulo: 'Iberdrola, resultados del primer semestre de 2026', url: 'https://www.cnmv.es/webservices/verdocumento/ver?t=%7B55516fd0-0e09-413c-a247-d6aed7d2d882%7D', nota: 'Resultados, balance y guía.' },
    { titulo: 'Histórico bursátil de Iberdrola', url: 'https://www.bolsarama.es/cotizacion/iberdrola', nota: 'Precio y rentabilidad anual.' },
    { titulo: 'IBEX 35', url: 'https://www.meff.es/esp/Derivados-Financieros/Ficha/FIE_IBEX_35', nota: 'Cierre de referencia del índice.' },
  ],
  limites: 'La empresa no publica todavía alquiler, rentabilidad del proyecto, capital exacto aportado o calendario detallado. Potencia de conexión, carga IT y cartera potencial son medidas distintas.',
}
