export default {
  id: 'redeia', nombre: 'Redeia', ticker: 'BME: RED',
  categoria: 'Red de transporte regulada', fecha: '1 septiembre 2026',
  sobrelinea: 'El cuello de botella eléctrico, comprado a través de una utility regulada',
  descripcion: 'Tesis técnica de Redeia: red eléctrica, demanda de centros de datos, regulación, capex, valoración y cotización.',
  tesisCorta: 'Redeia no cobra por servidores. Cobra por la red reconocida que permite conectarlos. La tesis depende de convertir un plan inversor récord en base regulada y caja, con el apagón todavía como riesgo.',
  lectura: 'Defensiva con crecimiento regulado',
  veredicto: 'Es el contraste más limpio con Merlin. Menos riesgo comercial y más riesgo regulatorio. El precio ofrece dividendo, pero la deuda y la ejecución del plan impiden tratarla como un bono.',
  horizonte: '2026 a 2029',
  mercado: {
    precio: '€15,28', fecha: '31/08/2026', fechaLarga: '31 de agosto de 2026',
    inicioYtd: '31/12/2025', inicioUnAno: '29/08/2025',
    ytd: 0.7, unAno: -8.0, ibexYtd: 15.4, ibexUnAno: 33.7, ibexCierre: '19.974,1',
    comentario: 'La acción ha quedado muy atrás del IBEX. El mercado todavía trata el aumento de inversión como una necesidad de financiación y ejecución, no como crecimiento ganado.',
    metodo: 'Precio BME en euros. €15,17 al 31/12/2025, €16,61 al 29/08/2025 y €15,28 al 31/08/2026. El IBEX usa el último cierre hábil comparable. Rentabilidad por precio, sin el dividendo de €0,80.',
  },
  metricas: [
    { etiqueta: 'Precio', valor: '€15,28', nota: 'Cierre del 31/08/2026' },
    { etiqueta: 'Rentabilidad 12 meses', valor: '-8,0%', nota: 'IBEX 35: +33,7%' },
    { etiqueta: 'EBITDA 1S 2026', valor: '€672,6m', nota: '+5,8%' },
    { etiqueta: 'Capex 2026 a 2029', valor: '€6.500m', nota: '€6.000m para Red Eléctrica' },
    { etiqueta: 'Retribución financiera', valor: '6,58%', nota: 'Periodo regulatorio 2026 a 2031' },
  ],
  resumen: 'El registro documenta 548 nudos. Solo 104 publican margen de demanda y 444 no lo hacen. Hay 35.690 MW disponibles, 13.882 MW otorgados y 18.941 MW en curso. Es evidencia de congestión sistémica, no de que toda la cola pertenezca a centros de datos. Redeia captura el ciclo cuando la inversión se aprueba, entra en servicio y aumenta la base de activos regulados.',
  favor: [
    'La retribución financiera sube al 6,58%, cien puntos básicos más que en el periodo anterior.',
    'El plan destina unos €1.500m anuales a Red Eléctrica y busca una base regulada de €12.000m en 2029.',
    'Centros de datos, industria, ferrocarril y electrificación compiten por una red con poco margen.',
    'El 89% del EBITDA de 2025 procedió de negocios regulados, lo que limita riesgo de demanda directa.',
  ],
  contra: [
    'La deuda neta de €5.009m sigue siendo alta frente a la generación operativa.',
    'El capex precede al reconocimiento regulatorio y puede consumir caja antes de elevar EBITDA.',
    'El expediente por el apagón añade riesgo de sanción, reputación y cambios operativos.',
    'La disponibilidad puede mejorar o parte de las solicitudes puede no convertirse en demanda real.',
  ],
  miLectura: 'Redeia es la mejor tesis para comprar la restricción de red sin apostar por un operador. Pero el cuello de botella no da poder de fijación libre: la CNMC determina la remuneración. La variable decisiva es cuánto capex entra a tiempo en base regulada y a qué coste financiero.',
  exposicion: {
    intro: 'La exposición es sistémica. Redeia no tiene ficha de operador porque no posee centros de datos. Su activo es la red de transporte que conecta la demanda.',
    cadena: [
      { titulo: 'Solicitud', texto: 'El promotor pide acceso en un nudo con capacidad limitada.' },
      { titulo: 'Planificación', texto: 'El Estado y Red Eléctrica priorizan refuerzos y nuevas posiciones.' },
      { titulo: 'Inversión', texto: 'Redeia construye activos de transporte y los pone en servicio.' },
      { titulo: 'Remuneración', texto: 'La base reconocida obtiene la tasa regulada y amortización.' },
    ],
    proyectos: [
      { nombre: 'Capacidad de acceso por nudo', href: '/red-electrica', estado: 'Publicación 03/08/2026', lectura: '104 de 548 nudos con margen publicado. La página permite comprobar el cuello de botella sin atribuirlo a una sola empresa.' },
      { nombre: 'Plan de inversión 2026 a 2029', estado: 'En ejecución', lectura: '€6.000m para Red Eléctrica y objetivo de €12.000m de base regulada en 2029.' },
    ],
    nota: 'No sumamos demanda otorgada y en curso como si fuera consumo futuro. Las solicitudes pueden solaparse, cambiar o caducar.',
  },
  finanzas: {
    intro: 'El primer semestre muestra crecimiento, pero también la intensidad de capital del nuevo ciclo.',
    bloques: [
      { titulo: 'Resultados 1S 2026', filas: [['Ingresos', '€900,5m'], ['EBITDA', '€672,6m'], ['EBIT', '€422,6m'], ['Beneficio neto', '€280,4m']] },
      { titulo: 'Capital y balance', filas: [['Inversión total 1S', '€657,1m'], ['Transporte español', '€630,9m'], ['Deuda neta', '€5.009,4m'], ['Dividendo 2025', '€0,80']] },
    ],
    nota: 'La inversión en redes aumentó un 12%. Para el accionista importa la fecha de puesta en servicio, porque el gasto que no entra en base regulada tarda más en producir retorno.',
  },
  valoracion: {
    intro: 'La valoración combina un dividendo alto con apalancamiento y crecimiento regulado aún no cobrado.',
    bloques: [
      { etiqueta: 'Capitalización', valor: '≈ €8.268m', texto: '€15,28 por unos 541,1 millones de acciones.' },
      { etiqueta: 'PER 2025', valor: '≈ 16,4×', texto: 'Capitalización sobre €505,6m de beneficio neto.' },
      { etiqueta: 'EV / EBITDA 2025', valor: '≈ 10,6×', texto: 'Cálculo simple con deuda neta de cierre.' },
      { etiqueta: 'Rentabilidad dividendo', valor: '≈ 5,2%', texto: '€0,80 por acción. El plan prevé crecimiento anual del 2%.' },
    ],
    nota: 'La deuda neta sobre EBITDA 2025 ronda 4,35 veces. Un dividendo atractivo no compensa si la base regulada se retrasa o el coste de deuda absorbe la nueva remuneración.',
  },
  escenarios: [
    { nombre: 'Conservador', titulo: 'Capex retrasado', texto: 'La inversión queda por debajo del plan, aumenta la deuda y el crecimiento regulado llega tarde.' },
    { nombre: 'Base', titulo: 'Plan ejecutado', texto: 'Redeia invierte cerca de €1.500m al año y la base regulada se acerca a €12.000m en 2029.' },
    { nombre: 'Favorable', titulo: 'Red acelerada', texto: 'La planificación habilita más inversión, las puestas en servicio avanzan y el dividendo crece sin elevar apalancamiento.' },
  ],
  seguimiento: [
    { indicador: 'Inversión anual', confirma: 'Cerca de €1.500m y alta proporción puesta en servicio.', alarma: 'Desviación material y repetida frente al plan.' },
    { indicador: 'Base regulada', confirma: 'Trayectoria visible hacia €12.000m en 2029.', alarma: 'Capex sin reconocimiento suficiente.' },
    { indicador: 'Deuda / EBITDA', confirma: 'Estabilización mientras crece la base.', alarma: 'Aumento sostenido o rebaja de rating.' },
    { indicador: 'Dividendo', confirma: 'Crecimiento del 2% anual financiado por caja.', alarma: 'Recorte o pago sostenido con más deuda.' },
    { indicador: 'Expediente del apagón', confirma: 'Sin sanción o provisión material.', alarma: 'Sanción relevante o marco más punitivo.' },
  ],
  fuentes: [
    { titulo: 'Redeia, resultados del primer semestre de 2026', url: 'https://www.redeia.com/es/sala-de-prensa/actualidad/nota-de-prensa/2026/07/redeia-incrementa-un-12-su-inversion-en-redes-para-industria-transicion-energetica-espana', nota: 'Resultados, inversión y deuda.' },
    { titulo: 'Redeia, resultados de 2025', url: 'https://www.redeia.com/en/press-office/news/press-release/2026/02/redeia-smashes-its-investment-record-1-551-billion-enable-energy-transition-spain', nota: 'EBITDA, beneficio y peso regulado.' },
    { titulo: 'Plan estratégico de Redeia', url: 'https://www.redeia.com/es/conocenos/plan-estrategico', nota: 'Capex, base regulada y dividendo.' },
    { titulo: 'CNMC, tasa de retribución 2026 a 2031', url: 'https://www.cnmc.es/en/node/417863?back=news', nota: 'Tasa financiera del 6,58%.' },
    { titulo: 'Histórico de Redeia', url: 'https://pt.investing.com/equities/red-electrica-historical-data', nota: 'Cierres bursátiles.' },
  ],
  limites: 'La cola de acceso no identifica por sí sola el uso final ni la probabilidad de conexión. El análisis no atribuye a centros de datos toda la inversión de red.',
}
