export default {
  id: 'solaria', nombre: 'Solaria', ticker: 'BME: SLR',
  categoria: 'Renovables, conexión y almacenamiento', fecha: '1 septiembre 2026',
  sobrelinea: 'Contratos digitales capaces de cambiar una compañía pequeña',
  descripcion: 'Tesis técnica de Solaria: acuerdos con Merlin, PPA, BESS, balance, valoración y cotización.',
  tesisCorta: 'Solaria vende acceso, infraestructura eléctrica, energía y almacenamiento a Merlin. La duración contractual es atractiva. La financiación y la calidad del beneficio son bastante menos cómodas.',
  lectura: 'Especulativa',
  veredicto: 'La exposición digital es material y el castigo bursátil ha sido severo. Todavía hace falta convertir contratos en obras, cobros recurrentes y menor deuda antes de llamar barata a la acción.',
  horizonte: '2026 a 2030',
  mercado: {
    precio: '€16,96', fecha: '31/08/2026', fechaLarga: '31 de agosto de 2026',
    inicioYtd: '31/12/2025', inicioUnAno: '29/08/2025',
    ytd: -4.1, unAno: 22.6, ibexYtd: 15.4, ibexUnAno: 33.7, ibexCierre: '19.974,1',
    comentario: 'La acción conserva ganancia anual, pero cae un 27,8% desde finales de mayo y un 29,3% frente al precio de la ampliación. El mercado ha reducido el valor de la opcionalidad sin eliminarlo.',
    metodo: 'Precio BME en euros. La ventana anual usa €13,835 al 29/08/2025. La ampliación se colocó a €24 en abril. Rentabilidad por precio, sin dividendos.',
  },
  metricas: [
    { etiqueta: 'Precio', valor: '€16,96', nota: 'Cierre del 31/08/2026' },
    { etiqueta: 'Desde la ampliación', valor: '-29,3%', nota: 'Precio de colocación €24' },
    { etiqueta: 'EBITDA 2025', valor: '€266,1m', nota: '+32%' },
    { etiqueta: 'Segundo acuerdo', valor: '213 MW', nota: 'Demanda del centro' },
    { etiqueta: 'PPA y batería', valor: '426 MWp + 600 MWh', nota: 'Magnitudes no sumables' },
  ],
  resumen: 'Solaria puede cobrar por acceso, obra eléctrica, un PPA solar de 40 años y almacenamiento durante 10 años. Esa combinación puede cambiar la duración de sus flujos. No significa que posea el centro de datos. Tampoco permite sumar 213 MW de demanda, 426 MWp solares y 600 MWh de energía almacenada.',
  favor: [
    'Los acuerdos con Merlin tienen duración y escala relevantes frente al tamaño de Solaria.',
    'Acceso, infraestructura, PPA y BESS crean varias fuentes posibles de margen.',
    'La ampliación aportó casi €300m para financiar el plan.',
    'La caída desde abril reduce parte de las expectativas incorporadas al precio.',
  ],
  contra: [
    'La deuda y el fondo de maniobra negativo aumentan el riesgo de ejecución y nueva dilución.',
    'Parte del EBITDA reciente procede de desarrollo y plusvalías, no de generación recurrente.',
    'El centro de 213 MW sigue sin ubicación pública, permisos u obras identificables.',
    'Puertollano está paralizado y no debe presentarse como activo en ejecución.',
  ],
  miLectura: 'Es la tesis con más convexidad y más formas de decepcionar. Los contratos pueden valer mucho si generan cobros identificables y deuda amortizable. Si el EBITDA depende de rotaciones y la inversión consume la ampliación antes de cobrar, el accionista habrá financiado una promesa de 40 años sin visibilidad de los primeros cinco.',
  exposicion: {
    intro: 'La economía digital de Solaria tiene capas distintas. Separarlas evita inflar la capacidad y permite seguir qué contrato produce caja.',
    cadena: [
      { titulo: 'Acceso y conexión', texto: 'Solaria aporta 213 MW de acceso para la demanda del segundo centro.' },
      { titulo: 'Infraestructura', texto: 'La compañía ejecutará instalaciones eléctricas asociadas.' },
      { titulo: 'Energía', texto: 'Un PPA de 426 MWp solares tendrá una duración anunciada de 40 años.' },
      { titulo: 'Almacenamiento', texto: 'El contrato BESS cubre 600 MWh durante 10 años.' },
    ],
    proyectos: [
      { nombre: 'PPA Merlin Solaria, 225 MW', estado: 'Contratado', lectura: 'Primer acuerdo con 445 MW solares durante 15 años. La ubicación del centro no está confirmada.' },
      { nombre: 'PPA Madrid, 426 MW', estado: 'Contratado', lectura: 'Asociado al segundo acuerdo de 213 MW de demanda.' },
      { nombre: 'BESS Madrid, 600 MWh', estado: 'Contratado', lectura: 'Almacenamiento durante 10 años. Debe seguirse separado de MW solares y MW IT.' },
      { nombre: 'Solaria DataSection Puertollano', href: '/proyecto/solaria-datasection-puertollano', estado: 'Paralizado', lectura: 'Sin servidores, obra eléctrica, socio o calendario acreditados a enero de 2026.' },
    ],
    nota: 'El acceso vasco de 225 MW y el primer acuerdo con Merlin pueden referirse al mismo proyecto. El registro evita contarlos dos veces sin prueba.',
  },
  finanzas: {
    intro: 'El crecimiento reportado es fuerte, pero la composición exige cuidado.',
    bloques: [
      { titulo: 'Ejercicio 2025', filas: [['Ingresos', '€303,4m'], ['EBITDA', '€266,1m'], ['Beneficio neto', '€137,4m'], ['Inversión', '€400m']] },
      { titulo: 'Primer trimestre 2026', filas: [['Ingresos', '€120,4m'], ['EBITDA reportado', '€113,2m'], ['Beneficio neto', '€80,4m'], ['Fondo de maniobra', '-€129,3m']] },
    ],
    nota: 'El trimestre incluye €49,6m de servicios de desarrollo y €37m de plusvalía por la entrada de Stoneshield en Gravyx. Sin esa plusvalía, el EBITDA rondaría €76m. No debe anualizarse el dato reportado.',
  },
  valoracion: {
    intro: 'El múltiplo ya atribuye valor a desarrollo, baterías y digital. El castigo bursátil no convierte automáticamente la opción en gratuita.',
    bloques: [
      { etiqueta: 'Capitalización', valor: '≈ €2.250m', texto: '€16,96 por unos 132,64 millones de acciones.' },
      { etiqueta: 'PER 2025', valor: '≈ 16,4×', texto: 'Precio frente al beneficio reportado, que incluye negocios de desarrollo.' },
      { etiqueta: 'Deuda neta proforma', valor: '≈ €1.130m', texto: 'Ilustración tras restar la captación, antes del capex y caja de 2026.' },
      { etiqueta: 'EV / EBITDA 2025', valor: '≈ 12,7×', texto: 'Con deuda proforma. Sin ese ajuste estaría más cerca de 13,5 veces.' },
    ],
    nota: 'La ampliación añadió 7,69 millones de acciones nuevas y diluyó alrededor de un 6,15%. La caja captada no puede restarse para siempre si ya financia capex.',
  },
  escenarios: [
    { nombre: 'Conservador', titulo: 'Capex antes que caja', texto: 'Merlin retrasa proyectos, el EBITDA depende de plusvalías y Solaria vuelve a ampliar capital.' },
    { nombre: 'Base', titulo: 'Contratos ejecutados', texto: 'Se construyen solar y BESS, aparecen cobros y la deuda neta mejora pese a la inversión.' },
    { nombre: 'Favorable', titulo: 'Plataforma Tier 1', texto: 'Los 500 MW en negociación se convierten en contratos y el modelo híbrido se replica.' },
  ],
  seguimiento: [
    { indicador: 'Cobros de Merlin', confirma: 'Ingresos de acceso e infraestructura separados y materiales.', alarma: 'No llegan antes de la decisión final del cliente.' },
    { indicador: 'Segundo centro', confirma: 'Ubicación, permisos, obras y fecha de energización.', alarma: '213 MW sin emplazamiento durante 2027.' },
    { indicador: 'EBITDA recurrente', confirma: 'Crecimiento sin depender de plusvalías.', alarma: 'Rotaciones necesarias para cumplir objetivos.' },
    { indicador: 'Deuda neta', confirma: 'Mejora después de la ampliación y pese al capex.', alarma: 'La captación se consume sin mayor caja operativa.' },
    { indicador: 'Capital social', confirma: 'No hay nueva ampliación antes de monetizar contratos.', alarma: 'Nueva dilución para financiar la cartera.' },
  ],
  fuentes: [
    { titulo: 'Solaria, segundo acuerdo con Merlin', url: 'https://solariaenergia.com/solaria-alcanza-un-nuevo-acuerdo-con-merlin-para-un-segundo-centro-de-datos-213mw-alimentado-por-un-ppa-hibrido/', nota: 'Acceso, PPA y almacenamiento.' },
    { titulo: 'Solaria, resultados de 2025', url: 'https://solariaenergia.com/en/solaria-exceeds-forecasts-with-record-ebitda-of-e266-million-32-and-increases-its-net-profit-to-e137-million-55-in-2025/', nota: 'Resultados anuales y previsiones digitales.' },
    { titulo: 'Solaria, resultados del primer trimestre de 2026', url: 'https://www.cnmv.es/webservices/verdocumento/ver?t=%7B0133e8d7-1008-4e0c-9cd4-9e11c8c9c604%7D', nota: 'Composición del EBITDA, balance y capex.' },
    { titulo: 'Histórico bursátil de Solaria', url: 'https://datosmacro.expansion.com/bolsa/espana?dr=2026-08&sc=ES0165386014', nota: 'Cierres y rentabilidad por precio.' },
  ],
  limites: 'Los acuerdos no publican toda la estructura de precios, hitos de cobro, capex o garantías. La estimación corporativa de ingresos a 40 años no es valor presente ni caja contratada hoy.',
}
